NDefines.NGame.END_DATE = "2050.5.23.12"
NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 25
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 25
NDefines.NMilitary.ARMY_LEADER_XP_GAIN_PER_UNIT_IN_COMBAT = 0.16
NDefines.NCountry.SPECIAL_FORCES_CAP_BASE = 0.10
NDefines.NCountry.SPECIAL_FORCES_CAP_MIN = 48
NDefines_Graphics.NFrontend.CAMERA_MIN_HEIGHT = 40.0
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 1000;
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 1000;
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 1000;
NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 10 	--Base cost to unlock a regiment slot,
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 4	--Base cost to change a regiment column.
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 8 	--Base cost to unlock a support slot
